# docker-compose.yml
version: '2'
services:
    prometheus:
        image: prom/prometheus:v2.0.0
        volumes:
            - prometheus_data:/prometheus
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
    node-exporter:
        image: prom/node-exporter:v0.15.1
    grafana:
        image: grafana/grafana:4.6.2
        ports: 
            - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=pass
        volumes:
            - grafana_data:/var/lib/grafana
        depends_on:
            - prometheus
volumes:
    prometheus_data: {}
    grafana_data: {}
